-- Script that converts a database to UTF-8
SELECT CONCAT("ALTER TABLE ", TABLE_SCHEMA, '.', TABLE_NAME, " COLLATE utf8mb4;") AS execStr FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA="hbtn_0c_0" AND TABLE_TYPE="BASE TABLE";
